package cn.zying.osales.pojos ;

import javax.persistence.Column ;
import javax.persistence.Entity ;
import javax.persistence.Table ;
import javax.persistence.Transient ;

import cn.zy.apps.tools.jpa.FieldDesc ;
import cn.zying.osales.pojos.commons.BaseProductInfo ;

// Generated 2013-6-20 10:53:13 by Hibernate Tools 3.4.0.CR1

/**
 * ProductInfo generated by hbm2java 产品信息
 */

@Entity
@Table(name = "base_product_info")
public class ProductInfo extends BaseProductInfo implements java.io.Serializable {

    // 商品类型
    //    @Column(name = "commodity_type")
    //    @FieldDesc(name = "商品类型")
    //    private CommodityType commodityType ;

    //    @Column(name = "stand_price")
    //    // 标准核准价
    //    private Long standPrice ;
    //
    //    @Transient
    //    private String standPriceMoneyShow ;
    //
    //    @Transient
    //    private String standPriceHide ;

    // 仓库平均单价
    @Column(name = "storehouse_average_tax_price")
    private Long storehouseAverageTaxPrice ;

    @Transient
    private String storehouseAverageTaxPriceMoneyShow ;

    @Transient
    private String storehouseAverageTaxPriceMoneyHide ;

    @Column(name = "last_stock_tax_price")
    @FieldDesc(name = "最后含税采购价", isShow = false)
    private Long lastStockTaxPrice ;

    @Transient
    @FieldDesc(name = "最后含税采购价", isShow = true)
    private String lastStockTaxPriceMoneyShow ;

    @Transient
    @FieldDesc(name = "最后含税采购价", isShow = false)
    private String lastStockTaxPriceMoneyHide ;

    @Column(name = "last_sales_tax_price")
    @FieldDesc(name = "最后含税销售价", isShow = false)
    private Long lastSalesTaxPrice ;

    @Transient
    @FieldDesc(name = "最后含税销售价", isShow = true)
    private String lastSalesTaxPriceMoneyShow ;

    @Transient
    @FieldDesc(name = "最后含税销售价", isShow = false)
    private String lastSalesTaxPriceMoneyHide ;

    public Long getStorehouseAverageTaxPrice() {
        return storehouseAverageTaxPrice ;
    }

    public void setStorehouseAverageTaxPrice(Long storehouseAverageTaxPrice) {
        this.storehouseAverageTaxPrice = storehouseAverageTaxPrice ;
    }

    public String getStorehouseAverageTaxPriceMoneyShow() {
        return storehouseAverageTaxPriceMoneyShow ;
    }

    public void setStorehouseAverageTaxPriceMoneyShow(String storehouseAverageTaxPriceMoneyShow) {
        this.storehouseAverageTaxPriceMoneyShow = storehouseAverageTaxPriceMoneyShow ;
    }

    public String getStorehouseAverageTaxPriceMoneyHide() {
        return storehouseAverageTaxPriceMoneyHide ;
    }

    public void setStorehouseAverageTaxPriceMoneyHide(String storehouseAverageTaxPriceMoneyHide) {
        this.storehouseAverageTaxPriceMoneyHide = storehouseAverageTaxPriceMoneyHide ;
    }

    public Long getLastStockTaxPrice() {
        return lastStockTaxPrice ;
    }

    public void setLastStockTaxPrice(Long lastStockTaxPrice) {
        this.lastStockTaxPrice = lastStockTaxPrice ;
    }

    public String getLastStockTaxPriceMoneyShow() {
        return lastStockTaxPriceMoneyShow ;
    }

    public void setLastStockTaxPriceMoneyShow(String lastStockTaxPriceMoneyShow) {
        this.lastStockTaxPriceMoneyShow = lastStockTaxPriceMoneyShow ;
    }

    public String getLastStockTaxPriceMoneyHide() {
        return lastStockTaxPriceMoneyHide ;
    }

    public void setLastStockTaxPriceMoneyHide(String lastStockTaxPriceMoneyHide) {
        this.lastStockTaxPriceMoneyHide = lastStockTaxPriceMoneyHide ;
    }

    public Long getLastSalesTaxPrice() {
        return lastSalesTaxPrice ;
    }

    public void setLastSalesTaxPrice(Long lastSalesTaxPrice) {
        this.lastSalesTaxPrice = lastSalesTaxPrice ;
    }

    public String getLastSalesTaxPriceMoneyShow() {
        return lastSalesTaxPriceMoneyShow ;
    }

    public void setLastSalesTaxPriceMoneyShow(String lastSalesTaxPriceMoneyShow) {
        this.lastSalesTaxPriceMoneyShow = lastSalesTaxPriceMoneyShow ;
    }

    public String getLastSalesTaxPriceMoneyHide() {
        return lastSalesTaxPriceMoneyHide ;
    }

    public void setLastSalesTaxPriceMoneyHide(String lastSalesTaxPriceMoneyHide) {
        this.lastSalesTaxPriceMoneyHide = lastSalesTaxPriceMoneyHide ;
    }

}
