package cn.zying.osales.pojos ;

import javax.persistence.Column ;
import javax.persistence.Entity ;
import javax.persistence.FetchType ;
import javax.persistence.JoinColumn ;
import javax.persistence.ManyToOne ;
import javax.persistence.Table ;

import cn.zying.osales.pojos.commons.StockDetailCommBean ;

// Generated 2013-6-20 10:53:13 by Hibernate Tools 3.4.0.CR1

/**
 * StockReturnDetail generated by hbm2java
 */

@Entity
@Table(name = "stock_return_detail")
public class StockReturnDetail extends StockDetailCommBean {

    // 采购订单
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "stock_return_id")
    private StockReturn stockReturn ;

    @Column(name = "stock_return_id", insertable = false, updatable = false)
    private Integer stockReturnId ;

    public StockReturn getStockReturn() {
        return stockReturn ;
    }

    public void setStockReturn(StockReturn stockReturn) {
        this.stockReturn = stockReturn ;
    }

    public Integer getStockReturnId() {
        return stockReturnId ;
    }

    public void setStockReturnId(Integer stockReturnId) {
        this.stockReturnId = stockReturnId ;
    }



}
