package cn.zying.osales.pojos ;

import java.util.List ;

import javax.persistence.CascadeType ;
import javax.persistence.Column ;
import javax.persistence.Entity ;
import javax.persistence.FetchType ;
import javax.persistence.JoinColumn ;
import javax.persistence.OneToMany ;
import javax.persistence.OneToOne ;
import javax.persistence.Table ;

import cn.zying.osales.pojos.commons.StockCommBean ;

// Generated 2013-6-20 10:53:13 by Hibernate Tools 3.4.0.CR1

/**
 * StockStoreGoods generated by hbm2java 采购进货单
 */

@Entity
@Table(name = "stock_store_receive")
public class StockStoreReceive extends StockCommBean {

    private static final long serialVersionUID = -53597895850663517L ;

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "stockStoreReceive")
    private List<StockStoreReceiveDetail> stockStoreReceiveDetails ;

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "stock_in_store_id")
    private StockInStore stockInStore ;

    @Column(name = "stock_in_store_id", insertable = false, updatable = false)
    private Integer stockInStoreId ;

    public List<StockStoreReceiveDetail> getStockStoreReceiveDetails() {
        return stockStoreReceiveDetails ;
    }

    public void setStockStoreReceiveDetails(List<StockStoreReceiveDetail> stockStoreReceiveDetails) {
        this.stockStoreReceiveDetails = stockStoreReceiveDetails ;
    }

    public StockInStore getStockInStore() {
        return stockInStore ;
    }

    public void setStockInStore(StockInStore stockInStore) {
        this.stockInStore = stockInStore ;
    }

    public Integer getStockInStoreId() {
        return stockInStoreId ;
    }

    public void setStockInStoreId(Integer stockInStoreId) {
        this.stockInStoreId = stockInStoreId ;
    }

}
