package cn.zying.osales.pojos ;

import javax.persistence.Column ;
import javax.persistence.Entity ;
import javax.persistence.FetchType ;
import javax.persistence.JoinColumn ;
import javax.persistence.ManyToOne ;
import javax.persistence.Table ;

import cn.zying.osales.pojos.commons.StockDetailCommBean ;

// Generated 2013-6-20 10:53:13 by Hibernate Tools 3.4.0.CR1

/**
 * StockOrderDetailInfo generated by hbm2java 采购订单明细
 */
@Entity
@Table(name = "stock_order_detail")
public class StockOrderDetail extends StockDetailCommBean {

    /**
     * 
     */
    private static final long serialVersionUID = -2635832467478461321L ;

    // 采购订单
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "stock_order_id")
    private StockOrder stockOrder ;

    @Column(name = "stock_order_id", insertable = false, updatable = false)
    private Integer stockOrderId ;

    public StockOrder getStockOrder() {
        return stockOrder ;
    }

    public void setStockOrder(StockOrder stockOrder) {
        this.stockOrder = stockOrder ;
    }

    public Integer getStockOrderId() {
        return stockOrderId ;
    }

    public void setStockOrderId(Integer stockOrderId) {
        this.stockOrderId = stockOrderId ;
    }

}
