package cn.zying.osales.pojos ;

// Generated 2013-6-20 10:53:13 by Hibernate Tools 3.4.0.CR1

import java.util.List ;

import javax.persistence.CascadeType ;
import javax.persistence.Column ;
import javax.persistence.Entity ;
import javax.persistence.FetchType ;
import javax.persistence.JoinColumn ;
import javax.persistence.OneToMany ;
import javax.persistence.OneToOne ;
import javax.persistence.Table ;

import cn.zy.apps.tools.jpa.FieldDesc ;
import cn.zying.osales.pojos.commons.StockCommBean ;

/**
 * StockStore generated by hbm2java 采购进货入库
 */

@Entity
@Table(name = "stock_in_store")
public class StockInStore extends StockCommBean {

    // 采购订单
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "stock_order_id")
    @FieldDesc(name = "采购订单订单号", mapping = "stockOrder.orderNumber")
    private StockOrder stockOrder ;

    @Column(name = "stock_order_id", insertable = false, updatable = false)
    private Integer stockOrderId ;

    // 采购进货入库明细l
    @OneToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL, mappedBy = "stockInStore")
    private List<StockInStoreDetail> stockInStoreDetails ;

    public StockOrder getStockOrder() {
        return stockOrder ;
    }

    public void setStockOrder(StockOrder stockOrder) {
        this.stockOrder = stockOrder ;
    }

    public Integer getStockOrderId() {
        return stockOrderId ;
    }

    public void setStockOrderId(Integer stockOrderId) {
        this.stockOrderId = stockOrderId ;
    }

    public List<StockInStoreDetail> getStockInStoreDetails() {
        return stockInStoreDetails ;
    }

    public void setStockInStoreDetails(List<StockInStoreDetail> stockInStoreDetails) {
        this.stockInStoreDetails = stockInStoreDetails ;
    }

}
