package cn.zying.osales.pojos ;

// Generated 2013-6-20 10:53:13 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column ;
import javax.persistence.Entity ;
import javax.persistence.FetchType ;
import javax.persistence.JoinColumn ;
import javax.persistence.ManyToOne ;
import javax.persistence.OneToOne ;
import javax.persistence.Table ;

import cn.zying.osales.pojos.commons.StockDetailCommBean ;

/**
 * StockStoreGoodsDetail generated by hbm2java
 */

@Entity
@Table(name = "stock_store_receive_detail")
public class StockStoreReceiveDetail extends StockDetailCommBean {

    private static final long serialVersionUID = -8354384848990307468L ;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "stock_store_receive_id")
    private StockStoreReceive stockStoreReceive ;

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "stock_in_store_detail_id")
    private StockInStoreDetail stockInStoreDetail ;

    @Column(name = "stock_in_store_detail_id", insertable = false, updatable = false)
    private Integer stockInStoreDetailId ;

    @Column(name = "stock_store_receive_id", insertable = false, updatable = false)
    private Integer stockStoreReceiveId ;

    public StockStoreReceive getStockStoreReceive() {
        return stockStoreReceive ;
    }

    public void setStockStoreReceive(StockStoreReceive stockStoreReceive) {
        this.stockStoreReceive = stockStoreReceive ;
    }

    public Integer getStockStoreReceiveId() {
        return stockStoreReceiveId ;
    }

    public void setStockStoreReceiveId(Integer stockStoreReceiveId) {
        this.stockStoreReceiveId = stockStoreReceiveId ;
    }

    public StockInStoreDetail getStockInStoreDetail() {
        return stockInStoreDetail ;
    }

    public void setStockInStoreDetail(StockInStoreDetail stockInStoreDetail) {
        this.stockInStoreDetail = stockInStoreDetail ;
    }

    public Integer getStockInStoreDetailId() {
        return stockInStoreDetailId ;
    }

    public void setStockInStoreDetailId(Integer stockInStoreDetailId) {
        this.stockInStoreDetailId = stockInStoreDetailId ;
    }

}
