package cn.zying.osales.pojos ;

// Generated 2013-6-20 10:53:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date ;

import javax.persistence.Column ;
import javax.persistence.Entity ;
import javax.persistence.FetchType ;
import javax.persistence.GeneratedValue ;
import javax.persistence.GenerationType ;
import javax.persistence.Id ;
import javax.persistence.JoinColumn ;
import javax.persistence.ManyToOne ;
import javax.persistence.Table ;
import javax.persistence.Temporal ;
import javax.persistence.TemporalType ;

/**
 * SystemLog generated by hbm2java
 */
@Entity
@Table(name = "system_log")
public class SystemLog implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Integer id ;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "system_user_id")
    private SystemUser systemUser ;

    @Column(name = "system_user_id", insertable = false, updatable = false)
    private Integer systemUserId ;

    // 做什么
    @Column(name = "what")
    private String what ;

    @Column(name = "date")
    @Temporal(TemporalType.DATE)
    private Date date ;

    @Column(name = "module_name")
    private String moduleName ;

    ;

    public SystemLog() {
    }

    public Integer getId() {
        return id ;
    }

    public void setId(Integer id) {
        this.id = id ;
    }

    public SystemUser getSystemUser() {
        return systemUser ;
    }

    public void setSystemUser(SystemUser systemUser) {
        this.systemUser = systemUser ;
    }

    public String getWhat() {
        return what ;
    }

    public void setWhat(String what) {
        this.what = what ;
    }

    public Date getDate() {
        return date ;
    }

    public void setDate(Date date) {
        this.date = date ;
    }

    public Integer getSystemUserId() {
        return systemUserId ;
    }

    public void setSystemUserId(Integer systemUserId) {
        this.systemUserId = systemUserId ;
    }

    public String getModuleName() {
        return moduleName ;
    }

    public void setModuleName(String moduleName) {
        this.moduleName = moduleName ;
    }

}
